### ISSUE TITLE
Project import error

### ISSUE THREAD

**Issue by Aatika-Fatima** [edgexfoundry/device-sdk-tools#20]
Eclipse throws an error on importing device-sdk-tools. 

![errror](https://user-images.githubusercontent.com/28926512/33543465-2633d7aa-d8fd-11e7-9926-8f216fc70502.PNG)

Kindly request you guide to fix above issue.

**Comment by trcox** [comment]
@Aatika-Fatima The device-sdk-tools repo is not a Maven project, please see the [Device Service SDK Getting Started Guide](https://wiki.edgexfoundry.org/display/FA/EdgeX+Foundry+SDK+that+Generates+the+Device+Service) for usage instructions and let me know if you have further questions!
